service: hmb-api

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-southeast-2

plugins:
  - serverless-webpack
  - serverless-offline

functions:
  hello:
    handler: src/endpoints/hello.hello
    events:
      - http: GET hello
  temperatureLogs:
    handler: src/endpoints/getTemperature.getTemperatureLog
    events:
      - http: GET temperatureLogs
