version: v1.0
name: Deploy HMB
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu1804
blocks:
  - name: Release
    task:
      secrets:
        - name: hmb-github
      jobs:
        - name: Release a new version
          commands:
            - checkout
            - BRANCH_NAME=master npx semantic-release
  - name: Deploy
    task:
      secrets:
        - name: aws-hold-my-beer
      jobs:
        - name: Deploy client to S3
          commands:
            - checkout
            - cd ./client/
            - cache restore client-dist-$SEMAPHORE_WORKFLOW_ID
            - cache restore client-scripts-$SEMAPHORE_WORKFLOW_ID
            - ./scripts/deploy.sh
        - name: Deploy API
          commands:
            - checkout
            - cd ./api/
            - cache restore serverless-build-$SEMAPHORE_WORKFLOW_ID
            - cache restore api-node-modules-$SEMAPHORE_WORKFLOW_ID
            - yarn deploy
