service: hmb-api

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-southeast-2

plugins:
  - serverless-webpack
  - serverless-offline

functions:
  hello:
    handler: src/endpoints/hello.hello
    environment:
      logsBucketName: ${file(./.env.yml):logsBucketName}
      logFilePath: ${file(./.env.yml):logFilePath}
    events:
      - http: GET hello
  temperatureLogs:
    handler: src/endpoints/getTemperature.getTemperatureLog
    environment:
      logsBucketName: ${file(./.env.yml):logsBucketName}
      logFilePath: ${file(./.env.yml):logFilePath}
    events:
      - http: GET temperatureLogs
