service: hmb-api

provider:
  name: aws
  runtime: nodejs10.x
  region: ap-southeast-2

plugins:
  - serverless-webpack
  - serverless-offline

functions:
  hello:
    handler: src/endpoints/hello.hello
    events:
      - http:
          method: get
          cors: true
          path: hello

  getProjects:
    handler: src/endpoints/getProjects.getProjects
    environment:
      projectsFileName: ${file(./.env.yml):projectsFileName}
      logsBucketName: ${file(./.env.yml):logsBucketName}
    events:
      - http:
          method: get
          cors: true
          path: projects

  getProject:
    handler: src/endpoints/getProjects.getProject
    environment:
      projectsFileName: ${file(./.env.yml):projectsFileName}
      logsBucketName: ${file(./.env.yml):logsBucketName}
    events:
      - http:
          method: get
          cors: true
          path: projects/{projectName}

  listLogFiles:
    handler: src/endpoints/listLogs.listLogFiles
    environment:
      logsBucketName: ${file(./.env.yml):logsBucketName}
      logsPath: ${file(./.env.yml):logsPath}
    events:
      - http:
          method: get
          cors: true
          path: logFiles/{type}

  recentTemperatureLogs:
    handler: src/endpoints/recentTemperatureLogs.recentTemperatureLogs
    environment:
      logsBucketName: ${file(./.env.yml):logsBucketName}
      logsPath: ${file(./.env.yml):logsPath}
    events:
      - http:
          method: get
          cors: true
          path: recentTemperatureLogs/{logFile}
          request:
            parameters:
              paths:
                logFile: true

  getMetadata:
    handler: src/endpoints/getMetadata.getMetadata
    environment:
      logsBucketName: ${file(./.env.yml):logsBucketName}
      logsPath: ${file(./.env.yml):logsPath}
    events:
      - http:
          method: get
          cors: true
          path: getMetadata/{logFile}
          request:
            parameters:
              paths:
                logFile: true

  temperature:
    handler: src/endpoints/downsampledTemperatureLogs.downsample
    environment:
      logsBucketName: ${file(./.env.yml):logsBucketName}
      logsPath: ${file(./.env.yml):logsPath}
    events:
      - http:
          method: get
          cors: true
          path: temperature/{logFile}
          request:
            parameters:
              paths:
                logFile: true
              querystrings:
                pointsCount: false
                downsamplingMethod: false

  gravity:
    handler: src/endpoints/gravityLogs.getGravityLog
    environment:
      logsBucketName: ${file(./.env.yml):logsBucketName}
      logsPath: ${file(./.env.yml):logsPath}
    events:
      - http:
          method: get
          cors: true
          path: gravity/{logFile}
          request:
            parameters:
              paths:
                logFile: true
              querystrings:
                last: false
