service: hmb-api

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-southeast-2

plugins:
  - serverless-webpack
  - serverless-offline

functions:
  hello:
    handler: src/endpoints/hello.hello
    events:
      - http:
          method: get
          path: hello

  recentTemperatureLogs:
    handler: src/endpoints/recentTemperatureLogs.recentTemperatureLogs
    environment:
      logsBucketName: ${file(./.env.yml):logsBucketName}
      logFilePath: ${file(./.env.yml):logFilePath}
    events:
      - http: GET recentTemperatureLogs

  listLogFiles:
    handler: src/endpoints/listTemperatureLogs.listLogFiles
    environment:
      logsBucketName: ${file(./.env.yml):logsBucketName}
      logsPath: ${file(./.env.yml):logsPath}
    events:
      - http:
          method: get
          path: logFiles

  temperature:
    handler: src/endpoints/downsampledTemperatureLogs.downsample
    environment:
      logsBucketName: ${file(./.env.yml):logsBucketName}
      logFilePath: ${file(./.env.yml):logFilePath}
    events:
      - http:
          method: get
          path: temperature
          request:
            parameters:
              querystrings:
                pointsCount: false
                downsamplingMethod: false
