service: hmb-api

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-southeast-2

plugins:
  - serverless-webpack
  - serverless-offline

functions:
  hello:
    handler: src/endpoints/hello.hello
    environment:
      logsBucketName: ${file(./.env.yml):logsBucketName}
      logFilePath: ${file(./.env.yml):logFilePath}
    events:
      - http: GET hello
  recentTemperatureLogs:
    handler: src/endpoints/recentTemperatureLogs.recentTemperatureLogs
    environment:
      logsBucketName: ${file(./.env.yml):logsBucketName}
      logFilePath: ${file(./.env.yml):logFilePath}
    events:
      - http: GET recentTemperatureLogs
  overallTemperatureLogs:
    handler: src/endpoints/overallTemperatureLogs.overallTemperatureLogs
    environment:
      logsBucketName: ${file(./.env.yml):logsBucketName}
      logFilePath: ${file(./.env.yml):logFilePath}
    events:
      - http: GET overallTemperatureLogs
